name: Flutter iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
        architecture: x64 # optional, x64 or arm64

    - name: Install dependencies
      run: flutter pub get

    # - name: Run tests
    # - run: flutter test

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Build iOS archive bundle
      run: flutter build ipa --release --no-codesign
